#'---
#'title: "Pediatric Blood Pressure Distributions"
#'output:
#'  rmarkdown::html_vignette:
#'    toc: true
#'    number_sections: true
#'bibliography: references.bib
#'resource_files:
#'  - '../man/figures/flowchart.png'
#'vignette: >
#'  %\VignetteIndexEntry{Pediatric Blood Pressure Distributions}
#'  %\VignetteEngine{knitr::rmarkdown}
#'  %\VignetteEncoding{UTF-8}
#'---
#'
#+ label = "setup", include = FALSE
#/*
devtools::load_all() # load the dev version while editing
require("svglite") # needed for saving svg images
#*/
################################################################################
#                        !!! DO NOT EDIT .Rmd files !!!                        #
#                                                                              #
# .Rmd files are generated by their corresponding .R files found in the        #
# vignette-spinners/ directory.  Any changes needed to the .Rmd file need to   #
# be made in the .R file                                                       #
################################################################################
knitr::opts_chunk$set(collapse = TRUE, fig.align = "center")
library(qwraps2)

#'
#'
#+ label = "helper functions", include = FALSE
percentile_factor <- function(p) {
  factor(p, levels = sort(unique(p)), labels = paste0(sort(unique(p)) * 100, "th"))
}

#'
#'
library(pedbp)
#'
#' # Introduction
#'
#' Part of the work of @martin2022machine required transforming blood
#' pressure measurement into percentiles based on published norms.  This
#' work was complicated by the fact that data for pediatric blood pressure
#' percentiles is sparse and generally only applicable to children at least one
#' year of age and requires height, a commonly unavailable data point in
#' electronic health records for a variety of reasons.
#'
#' A solution to building pediatric blood pressure percentiles was developed and
#' is presented here for others to use.  Inputs for the developed method are:
#'
#' 1. Patient sex (male/female) _required_
#' 2. Systolic blood pressure (mmHg) _required_
#' 3. Diastolic blood pressure (mmHg) _required_
#' 4. Patient height (cm) _if known_.
#'
#' Given the inputs, the following logic is used to determine which data sets
#' will be used to inform the blood pressure percentiles.  Under one year of
#' age, the data from @gemelli1990longitudinal will be used; a height input is
#' not required for this patient subset. For those at least one year of age with
#' a known height, data from @nhlbi2011expert (hereafter referred to as
#' 'NHLBI/CDC' as the report incorporates recommendations and inputs from the
#' National Heart, Lung, and Blood Institute [NHLBI] and the Centers for Disease
#' Control and Prevention [CDC]). If height is unknown and age is at least three
#' years, then data from @lo2013prehypertension is used.  Lastly, for children
#' between one and three years of age with unknown height, blood pressure
#' percentiles are estimated by the NHLBI/CDC data using as a default the median
#' height for each patient's sex and age.
#'
#' <img src = "../man/figures/flowchart.png"/>
#'
#' # Estimating Pediatric Blood Pressure Distributions
#'
#' There are two functions provided for working with blood pressure
#' distributions.  These methods use Gaussian distributions for both systolic
#' and diastolic blood pressures with means and standard deviations either
#' explicitly provided in an aforementioned source or derived by optimizing the parameters
#' such that the sum of squared errors between the provided quantiles from an
#' aforementioned source and the distribution quantiles is minimized.  The
#' provided functions, a distribution function and a quantile function, follow a
#' similar naming convention to the distribution functions found in the stats
#' library in R.
#'
#+ Distribution Function
args(p_bp)

# Quantile Function
args(q_bp)
#'
#'
#' Both methods expect an age in months and an indicator for sex.  If height is
#' missing, e.g., NA, then the default height percentile of 50 will be used as
#' applicable based on the patient's age group.  The end user may modify the
#' default height percentile.
#'
#' If height is entered, then the height percentile is determined via an LMS
#' method for age and sex using corresponding LMS data from the CDC (more
#' information on LMS methods and data is provided later in this vignette). The
#' parameters for the blood pressure distribution are found in a look up table
#' using the nearest age and height percentile.
#'
#' ## Percentiles
#'
#' What percentile for systolic and diastolic blood pressure is 100/60 for a 44
#' month old male with unknown height?
#'
p_bp(q_sbp = 100, q_dbp = 60, age = 44, male = 1)
#'
#' Those percentiles would be modified if height was 183 cm:
p_bp(q_sbp = 100, q_dbp = 60, age = 44, male = 1, height = 183)
#'
#' The package can also be used to determine the blood pressure percentiles
#' corresponding to a child of a given height percentile.
#' First find the height quantile using the q_height_for_age function, and then
#' use this height measurement (provided in centimeters) as the height input for
#' the
{{ qwraps2::backtick(p_bp) }}
#' function.
#+
ht <- q_height_for_age(p = 0.90, age = 44, male = 1)
ht

p_bp(q_sbp = 100, q_dbp = 60, age = 44, male = 1, height = ht)

#'
#' A plotting method to show where the observed blood pressures are on the
#' distribution function is also provided.
#+ fig.width = 5, fig.height = 5
bp_cdf(age = 44, male = 1, height = ht, sbp = 100, dbp = 60)

#'
#'
# /*
ggplot2::ggsave(file = "inst/images/fig3.svg", plot = bp_cdf(age = 44, male = 1, height = ht, sbp = 100, dbp = 60))
# */
#'
#' Vectors of blood pressures can be used as well.  NA values will return NA.
bps <-
  p_bp(
         q_sbp  = c(100, NA, 90)
       , q_dbp  = c(60, 82, 48)
       , age    = 44
       , male   = 1
       , height = ht
      )
bps
#'
#' If you want to know which data source was used in computing each of the
#' percentile estimates you can look at the
{{ qwraps2::backtick(bp_params) }}
#' attribute:
attr(bps, "bp_params")
str(bps)

#'
#' ## Quantiles
#'
#' If you have a percentile value and want to know the associated
#' systolic and diastolic blood pressures:
#'
q_bp(
       p_sbp = c(0.701, NA, 0.36)
     , p_dbp = c(0.85, 0.99, 0.50)
     , age = 44
     , male = 1
     , height = ht
    )
#'
#'
#' ## Working With More Than One Patient
#'
#' The
{{ qwraps2::backtick(p_bp) }}
#' and
{{ qwraps2::backtick(q_bp) }}
#' methods are designed accept vectors for each of the arguments.
#' These methods expected each argument to be length 1 or all the same length.
#'
#+ label = "bp_batch_example"
eg_data <- read.csv(system.file("example_data", "for_batch.csv", package = "pedbp"))
eg_data

bp_percentiles <-
  p_bp(
         q_sbp  = eg_data$sbp..mmHg.
       , q_dbp  = eg_data$dbp..mmHg.
       , age    = eg_data$age
       , male   = eg_data$male
       , height = eg_data$height
       )
bp_percentiles

str(bp_percentiles)

#'
#' Going from percentiles back to quantiles:
q_bp(
       p_sbp  = bp_percentiles$sbp_percentile
     , p_dbp  = bp_percentiles$dbp_percentile
     , age    = eg_data$age
     , male   = eg_data$male
     , height = eg_data$height
     )

#'
#' # Blood Pressure Charts
#'
#' ## When Height is Unknown or Irrelevant
#'
#' The following graphic shows the percentile curves by age and sex when height
#' is unknown, or irrelevant (for those under 12 months of age).
#'
#+ label = "chart1_setup", echo = FALSE
d <- data.table::CJ(male = 0:1
                    , age = seq(min(bp_parameters$age), max(bp_parameters$age), by = 0.5)
                    , bp_percentile = c(5, 10, 25, 50, 75, 90, 95) / 100)

x <- q_bp(d$bp_percentile, d$bp_percentile, age = d$age, male = d$male)
d <- cbind(d, source = attr(x, "bp_params")$source, sbp = x$sbp, dbp = x$dbp)

d <- data.table::melt(d
                      , id.vars = c("source", "male", "age", "bp_percentile")
                      , measure.vars = c("sbp", "dbp")
                      )
d[, variable := factor(variable, c("sbp", "dbp"), c("Systolic", "Diastolic"))]
d[, bp_percentile := percentile_factor(bp_percentile)]

bkgrnd <-
  data.table::data.table(
      source = c("Gemelli", "NHLBI", "Lo")
    , xmin   = c(0, 12, 36)
    , xmax   = c(12, 36, 204)
    , ymin   = rep(-Inf, 3)
    , ymax   = rep(Inf, 3)
    )

g <- function(d) {
  ggplot2::ggplot(d) +
    ggplot2::theme_bw() +
    ggplot2::aes(x = age, y = value, linetype = variable, color = bp_percentile) +
    ggplot2::geom_rect(data = bkgrnd
                       , inherit.aes = FALSE
                       , alpha = 0.3
                       , mapping = ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = source)) +
    ggplot2::geom_line() +
    ggplot2::facet_grid( ~ factor(male, 0:1, c("Female", "Male"))) +
    ggplot2::scale_x_continuous(name = "Age"
                                , breaks = seq(0, max(d$age) + 12, by = 12)
                                , labels = paste(
                                                   paste0(seq(0, max(d$age) + 12, by = 12), "m")
                                                 , paste0(seq(0, max(d$age) + 12, by = 12) / 12, "yr")
                                                 , sep = "\n")
                                ) +
    ggplot2::scale_y_continuous(name = "mmHg",breaks=c(0, 30, 60, 90, 120), limits = c(15, 140)) +
    ggplot2::scale_linetype(name = "") +
    ggplot2::scale_color_hue(name = "BP\nPercentile") +
    ggplot2::scale_fill_manual(name = "Data\nSource", values = c("Gemelli" = ggplot2::alpha("#236192", 0.5)
                                                                , "NHLBI"  = ggplot2::alpha("#6F263D", 0.5)
                                                                , "Lo"     = ggplot2::alpha("#A2AAAD", 0.5)
                                                                )) +
    ggplot2::guides(
                    linetype = ggplot2::guide_legend(order = 1, ncol = 1),
                    fill     = ggplot2::guide_legend(order = 2, ncol = 1),
                    color    = ggplot2::guide_legend(order = 3, ncol = 4)
                    ) +
    ggplot2::theme(
                   legend.position = "bottom"
                   )
}
#'
#'
#+ label = "chart1_female", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 0])
#'
# /*
# output svg for manuscript
ggplot2::ggsave(file = "inst/images/bp_percentile_female_height_unknown.svg", plot = g(d[male == 0]))
# */
#'
#+ label = "chart1_male", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 1])
#'
# /*
ggplot2::ggsave(file = "inst/images/bp_percentile_male_height_unknown.svg", plot = g(d[male == 1]))
# */
#'
#' ## Median Blood Pressures -- Varying default height percentile
#'
#' If height is unknown, there will be no difference in the estimated percentile
#' for blood pressures when modifying the default height_percentile with the
#' exception of values for patients between the ages of 12 and 36 months.
#' Patients under 12 months of age have percentiles estimated using data from
#' @gemelli1990longitudinal which does not consider height (length).  For
#' patients over 36 months of age data from @lo2013prehypertension, which also
#' does not consider height, is used.
#'
#' The following graphic shows the median blood pressure in mmHg by age when
#' varying the default height percentile used.  The colors refer to the height
#' percentile.
#'
#+ label = "chart2_setup", echo = FALSE, results = FALSE
d <- data.table::CJ(male = 0:1
                    # , age = unique(bp_parameters$age)
                    , age = seq(min(bp_parameters$age), max(bp_parameters$age), by = 0.5)
                    , bp_percentile = 50 / 100
                    , height_percentile = unique(na.omit(bp_parameters$height_percentile)) / 100)

x <- q_bp(d$bp_percentile, d$bp_percentile, age = d$age, male = d$male)
d <- cbind(d, source = attr(x, "bp_params")$source, sbp = x$sbp, dbp = x$dbp)
d <- data.table::melt(d
                      , id.vars = c("source", "male", "age", "bp_percentile","height_percentile")
                      , measure.vars = c("sbp", "dbp")
                      )
d[, variable := factor(variable, c("sbp", "dbp"), c("Systolic", "Diastolic"))]
d[, height_percentile := percentile_factor(height_percentile)]
d <- subset(d, age <= 84)
d[, range(age), by = .(source)]
bkgrnd <-
  data.table::data.table(
      source = c("Gemelli", "NHLBI", "Lo")
    , xmin   = c(0, 12, 36)
    , xmax   = c(12, 36, max(d$age))
    , ymin   = rep(-Inf, 3)
    , ymax   = rep(Inf, 3)
    )

g <- function(d) {
  ggplot2::ggplot(d) +
    ggplot2::theme_bw() +
    ggplot2::aes(x = age, y = value, linetype = variable, color = height_percentile) +
    ggplot2::geom_rect(data = bkgrnd
                       , inherit.aes = FALSE
                       , alpha = 0.3
                       , mapping = ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = source)) +
    ggplot2::geom_line() +
    ggplot2::facet_grid( ~ factor(male, 0:1, c("Female", "Male"))) +
    ggplot2::scale_x_continuous(name = "Age"
                                , breaks = seq(0, 84, by = 12)
                                , labels = paste(
                                                   paste0(seq(0, 84, by = 12), "m")
                                                 , paste0(seq(0, 84, by = 12) / 12, "yr")
                                                 , sep = "\n")
                                ) +
    ggplot2::scale_y_continuous(name = "Median BP (mmHg)",breaks=c(0, 30, 60, 90, 120), limits = c(15, 140)) +
    ggplot2::scale_linetype(name = "") +
    ggplot2::scale_color_hue(name = "Height\nPercentile") +
    ggplot2::scale_fill_manual(name = "Data\nSource", values = c("Gemelli" = ggplot2::alpha("#236192", 0.5)
                                                                , "NHLBI"  = ggplot2::alpha("#6F263D", 0.5)
                                                                , "Lo"     = ggplot2::alpha("#A2AAAD", 0.5)
                                                                )) +
    ggplot2::guides(
                    linetype = ggplot2::guide_legend(order = 1, ncol = 1),
                    fill     = ggplot2::guide_legend(order = 2, ncol = 1),
                    color    = ggplot2::guide_legend(order = 3, ncol = 4)
                    ) +
    ggplot2::theme(
                   legend.position = "bottom"
                   )
}
#'
#'
#+ label = "chart2_female", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 0])
#'
# /*
ggplot2::ggsave(file = "inst/images/median_bp_female_variable_default_height_percentile.svg", plot = g(d[male == 0]))
# */
#'
#+ label = "chart2_male", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 1])
#'
# /*
ggplot2::ggsave(file = "inst/images/median_bp_male_variable_default_height_percentile.svg", plot = g(d[male == 1]))
# */
#'
#' ## Median Blood Pressures for Children with Known Heights
#'
#' The following chart shows the median blood pressure by age for different
#' heights based on percentiles for age.
#'
#+ label = "chart3", echo = FALSE, results = "hide"
d <- data.table::CJ(male = 0:1
                    , age = seq(min(bp_parameters$age), max(bp_parameters$age), by = 0.5)
                    , bp_percentile = 50 / 100
                    , height_percentile = unique(na.omit(bp_parameters$height_percentile)) / 100)

d[, height := NA_real_]
d[age < 36, height := q_length_for_age(p = height_percentile, male = male, age = age), by = .(male, age, height_percentile)]
d[age >= 36, height := q_height_for_age(p = height_percentile, male = male, age = age), by = .(male, age, height_percentile)]

x <- q_bp(d$bp_percentile, d$bp_percentile, age = d$age, male = d$male)
d <- cbind(d, source = attr(x, "bp_params")$source, sbp = x$sbp, dbp = x$dbp)

d <- data.table::melt(d
                      , id.vars = c("source", "male", "age", "bp_percentile", "height_percentile")
                      , measure.vars = c("sbp", "dbp")
                      )

d[, variable := factor(variable, c("sbp", "dbp"), c("Systolic", "Diastolic"))]
d[, height_percentile := percentile_factor(height_percentile)]

d[, .(xmin = min(age), xmax = max(age)), by = .(source)]
bkgrnd <- data.table::data.table(source = c("Gemelli", "NHLBI"), xmin = c(0, 12), xmax = c(12, max(d$age)), ymin = c(-Inf, -Inf), ymax = c(Inf, Inf))

g <- function(d) {
  ggplot2::ggplot(d) +
    ggplot2::theme_bw() +
    ggplot2::geom_rect(data = bkgrnd
                       , inherit.aes = FALSE
                       , alpha = 0.3
                       , mapping = ggplot2::aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = source)) +
    ggplot2::aes(x = age, y = value, linetype = variable, color = height_percentile) +
    ggplot2::geom_line() +
    ggplot2::facet_grid( ~ factor(male, 0:1, c("Female", "Male"))) +
    ggplot2::scale_x_continuous(name = "Age"
                                , breaks = seq(0, max(d$age) + 12, by = 12)
                                , labels = paste(
                                                   paste0(seq(0, max(d$age) + 12, by = 12), "m")
                                                 , paste0(seq(0, max(d$age) + 12, by = 12) / 12, "yr")
                                                 , sep = "\n")
                                ) +
    ggplot2::scale_y_continuous(name = "Median BP (mmHg)",breaks=c(0, 30, 60, 90, 120), limits = c(15, 140)) +
    ggplot2::scale_linetype(name = "") +
    ggplot2::scale_color_hue(name = "Height\nPercentile") +
    ggplot2::scale_fill_manual(name = "Data\nSource", values = c("Gemelli" = ggplot2::alpha("#236192", 0.5)
                                                                , "NHLBI"  = ggplot2::alpha("#6F263D", 0.5)
                                                                , "Lo"     = ggplot2::alpha("#A2AAAD", 0.5)
                                                                )) +
    ggplot2::guides(
                    linetype = ggplot2::guide_legend(order = 1, ncol = 1),
                    fill     = ggplot2::guide_legend(order = 2, ncol = 1),
                    color    = ggplot2::guide_legend(order = 3, ncol = 4)
                    ) +
    ggplot2::theme(
                   legend.position = "bottom"
                   # , legend.direction = "vertical"
                   )
}
#'
#'
#+ label = "chart3_female", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 0])
# /*
ggplot2::ggsave(file = "inst/images/median_bp_female_known_height.svg", plot = g(d[male == 0]))
# */

#'
#'
#+ label = "chart3_male", echo = FALSE, fig.width = 8, fig.height = 6
g(d[male == 1])
# /*
ggplot2::ggsave(file = "inst/images/median_bp_male_known_height.svg", plot = g(d[male == 1]))
# */

#'
#' # Select Source Data
#'
#' The default method for estimating blood pressure percentiles is based on the
#' method of @martin2022machine and @martin2022development which uses three
#' different references depending on age and known/unknown stature.  If you want
#' to use a specific reference then you can do so by using the
{{ qwraps2::backtick(source) }}
#' argument.
#'
#' If you have a project with the want/need to use a specific source and you'd
#' to use you can set it as an option:
#'
#+ eval = FALSE
# /*
while (FALSE) {
# */
options("pedbp_bp_source", "martin2022")  # default
# /*
}
# */
#'
#' There are four sources:
#'
#' 1. @gemelli1990longitudinal for kids under one year of age.
#' 2. @lo2013prehypertension for kids over three years of age and when height is unknown.
#' 3. @nhlbi2011expert for kids 1 through 18 years of age with known stature.
#' 4. @flynn2017clinical for kids 1 through 18 years of age with known stature.
#'
#' The data from @flynn2017clinical and @nhlbi2011expert are similar but for one
#' major difference.  @flynn2017clinical excluded overweight and obese ( BMI
#' above the 85th percentile) children.
#'
#' For example, the estimated percentile for a blood pressure of 92/60 in a 29.2
#' month old female in the 95th height percentile are:
#'
p_bp(q_sbp = 92, q_dbp = 60, age = 29.2, male = 0, height_percentile = 0.95, source = "martin2022") # default
p_bp(q_sbp = 92, q_dbp = 60, age = 29.2, male = 0, height_percentile = 0.95, source = "gemelli1990")
p_bp(q_sbp = 92, q_dbp = 60, age = 29.2, male = 0, height_percentile = 0.95, source = "lo2013")
p_bp(q_sbp = 92, q_dbp = 60, age = 29.2, male = 0, height_percentile = 0.95, source = "nhlbi")
p_bp(q_sbp = 92, q_dbp = 60, age = 29.2, male = 0, height_percentile = 0.95, source = "flynn2017")

#'
#' The estimated 85th quantile SBP/DBP for a 29.2 month old female, who is in
#' the 95th height percentile are:
#'
q_bp(p_sbp = 0.85, p_dbp = 0.85, age = 29.2, male = 0, height_percentile = 0.95, source = "martin2022") # default
q_bp(p_sbp = 0.85, p_dbp = 0.85, age = 29.2, male = 0, height_percentile = 0.95, source = "gemelli1990")
q_bp(p_sbp = 0.85, p_dbp = 0.85, age = 29.2, male = 0, height_percentile = 0.95, source = "lo2013")
q_bp(p_sbp = 0.85, p_dbp = 0.85, age = 29.2, male = 0, height_percentile = 0.95, source = "nhlbi")
q_bp(p_sbp = 0.85, p_dbp = 0.85, age = 29.2, male = 0, height_percentile = 0.95, source = "flynn2017")

#'
#'
#' # Comparing to Published Percentiles
#'
#' The percentiles published in @nhlbi2011expert and @flynn2017clinical where
#' used to estimate a Gaussian mean and standard deviation.  This was in part to
#' be consistent with the values from @gemelli1990longitudinal and
#' @lo2013prehypertension.  As a result, the calculated percentiles and
#' quantiles from the pedbp package will be slightly different from the
#' published values.
#'
# /*
#  NOTE: This is also in the test suite
# */
#'
#' ## Flynn et al.
#'
fq <-
  q_bp(
     p_sbp = flynn2017$bp_percentile/100,
     p_dbp = flynn2017$bp_percentile/100,
     male  = flynn2017$male,
     age   = flynn2017$age,
     height_percentile = flynn2017$height_percentile,
     source = "flynn2017")

fp <-
  p_bp(
     q_sbp = flynn2017$sbp,
     q_dbp = flynn2017$dbp,
     male  = flynn2017$male,
     age   = flynn2017$age,
     height_percentile = flynn2017$height_percentile,
     source = "flynn2017")

f_bp <-
  cbind(flynn2017,
        pedbp_sbp = fq$sbp,
        pedbp_dbp = fq$dbp,
        pedbp_sbp_percentile = fp$sbp_percentile * 100,
        pedbp_dbp_percentile = fp$dbp_percentile * 100
  )

#'
#' All the quantile estimates are within 2 mmHg:
stopifnot(max(abs(f_bp$pedbp_sbp - f_bp$sbp)) < 2)
stopifnot(max(abs(f_bp$pedbp_dbp - f_bp$dbp)) < 2)

#'
#' All the percentiles are within 2 percentile points:
#'
stopifnot(max(abs(f_bp$pedbp_sbp_percentile - f_bp$bp_percentile)) < 2)
stopifnot(max(abs(f_bp$pedbp_dbp_percentile - f_bp$bp_percentile)) < 2)


#'
#' ## NHLBI/CDC
#'
nq <-
  q_bp(
     p_sbp = nhlbi_bp_norms$bp_percentile/100,
     p_dbp = nhlbi_bp_norms$bp_percentile/100,
     male  = nhlbi_bp_norms$male,
     age   = nhlbi_bp_norms$age,
     height_percentile = nhlbi_bp_norms$height_percentile,
     source = "nhlbi")

np <-
  p_bp(
     q_sbp = nhlbi_bp_norms$sbp,
     q_dbp = nhlbi_bp_norms$dbp,
     male  = nhlbi_bp_norms$male,
     age   = nhlbi_bp_norms$age,
     height_percentile = nhlbi_bp_norms$height_percentile,
     source = "nhlbi")

nhlbi_bp <-
  cbind(nhlbi_bp_norms,
        pedbp_sbp = nq$sbp,
        pedbp_dbp = nq$dbp,
        pedbp_sbp_percentile = np$sbp_percentile * 100,
        pedbp_dbp_percentile = np$dbp_percentile * 100
  )


#'
#' All the quantile estimates are within 2 mmHg:
#'
stopifnot(max(abs(nhlbi_bp$pedbp_sbp - nhlbi_bp$sbp)) < 2)
stopifnot(max(abs(nhlbi_bp$pedbp_dbp - nhlbi_bp$dbp)) < 2)

#'
#' All the percentiles are within 2 percentile points:
#'
stopifnot(max(abs(nhlbi_bp$pedbp_sbp_percentile - nhlbi_bp$bp_percentile)) < 2)
stopifnot(max(abs(nhlbi_bp$pedbp_dbp_percentile - nhlbi_bp$bp_percentile)) < 2)

#'
#'
#+ echo = FALSE
fsbp <- ggplot2::ggplot(f_bp) +
  ggplot2::theme_bw() +
  ggplot2::aes(x = sbp, y = pedbp_sbp) +
  ggplot2::geom_point() +
  ggplot2::geom_abline(intercept = 0, slope = 1)
fdbp <- ggplot2::ggplot(f_bp) +
  ggplot2::theme_bw() +
  ggplot2::aes(x = dbp, y = pedbp_dbp) +
  ggplot2::geom_point() +
  ggplot2::geom_abline(intercept = 0, slope = 1)

ggpubr::ggarrange(fsbp, qwraps2::qblandaltman(f_bp[, c("sbp", "pedbp_sbp")]) + ggplot2::theme_bw(),
                  fdbp, qwraps2::qblandaltman(f_bp[, c("dbp", "pedbp_dbp")]) + ggplot2::theme_bw())


if (interactive()) {
  par(mfrow = c(1, 2))
  plot(f_bp$sbp, f_bp$pedbp_sbp); abline(0, 1)
  plot(f_bp$dbp, f_bp$pedbp_dbp); abline(0, 1)
  summary(f_bp$pedbp_sbp - f_bp$sbp)
  summary(f_bp$pedbp_dbp - f_bp$dbp)
  summary(f_bp$pedbp_sbp_percentile*100 - f_bp$bp_percentile)
  summary(f_bp$pedbp_dbp_percentile*100 - f_bp$bp_percentile)

  qwraps2::qblandaltman(f_bp[, c("sbp", "pedbp_sbp")])
  qwraps2::qblandaltman(f_bp[, c("dbp", "pedbp_dbp")])
  qwraps2::qblandaltman(f_bp[, c("bp_percentile", "pedbp_sbp_percentile")])
  qwraps2::qblandaltman(f_bp[, c("bp_percentile", "pedbp_dbp_percentile")])

  par(mfrow = c(1, 2))
  plot(nhlbi_bp$sbp, nhlbi_bp$pedbp_sbp); abline(0, 1)
  plot(nhlbi_bp$dbp, nhlbi_bp$pedbp_dbp); abline(0, 1)
  summary(nhlbi_bp$pedbp_sbp - nhlbi_bp$sbp)
  summary(nhlbi_bp$pedbp_dbp - nhlbi_bp$dbp)
  summary(nhlbi_bp$pedbp_sbp_percentile*100 - nhlbi_bp$bp_percentile)
  summary(nhlbi_bp$pedbp_dbp_percentile*100 - nhlbi_bp$bp_percentile)

  qwraps2::qblandaltman(nhlbi_bp[, c("sbp", "pedbp_sbp")])
  qwraps2::qblandaltman(nhlbi_bp[, c("dbp", "pedbp_dbp")])
  qwraps2::qblandaltman(nhlbi_bp[, c("bp_percentile", "pedbp_sbp_percentile")])
  qwraps2::qblandaltman(nhlbi_bp[, c("bp_percentile", "pedbp_dbp_percentile")])
}



#'
#'
#' # Shiny Application
#'
#' An interactive [Shiny](https://shiny.posit.co/) application is also
#' available. After installing the pedbp package and the suggested packages, you
#' can run the app locally via
#'
#+ label = "shiny", eval = FALSE
# /*
while (FALSE) {
# */
shiny::runApp(system.file("shinyapps", "pedbp", package = "pedbp"))
# /*
}
# */
#'
#' The shiny application allows for interactive exploration of blood pressure
#' percentiles for an individual patient and allows for batch processing a set
#' of patients as well.
#'
#' An example input file for batch processing is provided within the package an
#' can be accessed via:
#+ label = "shiny_batch_example_file", eval = FALSE
system.file("example_data", "for_batch.csv", package = "pedbp")

#'
#'
#'
#' # References
#'<div id="refs"></div>
#'
#' # Session Info
#+ label = "sessioninfo"
sessionInfo()
