// Generated by data-raw/gaussian_parameters.R
// Do not edit by hand
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
#include <Rcpp.h>
#ifndef pedbp_bp_params_H
#define pedbp_bp_params_H
arma::mat gemelli1990_female();
arma::mat gemelli1990_male();
arma::mat nhlbi_female();
arma::mat nhlbi_male();
arma::mat lo2013_female();
arma::mat lo2013_male();
arma::mat flynn2017_female();
arma::mat flynn2017_male();
#endif
