// Generated by data-raw/sysdata.R
// Do not edit by hand
#include <RcppArmadillo.h>
#include <Rcpp.h>
arma::mat bmi_for_age_cdc_female();
arma::mat bmi_for_age_cdc_male();
arma::mat bmi_for_age_who_female();
arma::mat bmi_for_age_who_male();
arma::mat head_circumference_for_age_cdc_female();
arma::mat head_circumference_for_age_cdc_male();
arma::mat stature_for_age_cdc_female();
arma::mat stature_for_age_cdc_male();
arma::mat stature_for_age_who_female();
arma::mat stature_for_age_who_male();
arma::mat weight_for_age_cdc_female();
arma::mat weight_for_age_cdc_male();
arma::mat weight_for_age_who_female();
arma::mat weight_for_age_who_male();
arma::mat weight_for_stature_cdc_female();
arma::mat weight_for_stature_cdc_male();
arma::mat weight_for_stature_who_female();
arma::mat weight_for_stature_who_male();
