// Generated by data-raw/sysdata.R
// Do not edit by hand
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
#include <Rcpp.h>
#ifndef pedbp_lms_data_H
#define pedbp_lms_data_H
arma::mat bmi_for_age_cdc_female();
arma::mat bmi_for_age_cdc_male();
arma::mat bmi_for_age_who_female();
arma::mat bmi_for_age_who_male();
arma::mat head_circumference_for_age_cdc_female();
arma::mat head_circumference_for_age_cdc_male();
arma::mat head_circumference_for_age_who_female();
arma::mat head_circumference_for_age_who_male();
arma::mat height_for_age_cdc_female();
arma::mat height_for_age_cdc_male();
arma::mat height_for_age_who_female();
arma::mat height_for_age_who_male();
arma::mat length_for_age_cdc_female();
arma::mat length_for_age_cdc_male();
arma::mat length_for_age_who_female();
arma::mat length_for_age_who_male();
arma::mat weight_for_age_cdc_female();
arma::mat weight_for_age_cdc_male();
arma::mat weight_for_age_who_female();
arma::mat weight_for_age_who_male();
arma::mat weight_for_height_cdc_female();
arma::mat weight_for_height_cdc_male();
arma::mat weight_for_height_who_female();
arma::mat weight_for_height_who_male();
arma::mat weight_for_length_cdc_female();
arma::mat weight_for_length_cdc_male();
arma::mat weight_for_length_who_female();
arma::mat weight_for_length_who_male();
#endif
