# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title LMS data and distribution estimates
#'
#' @param metric
#' @param male
#' @param source
#' @param age (in months)
#' @param stature (in cm)
#'
#' @export
cppPGSF <- function(metric, source, male, x, qp, type) {
    .Call('_pedbp_cppPGSF', PACKAGE = 'pedbp', metric, source, male, x, qp, type)
}

