# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Pediatric Growth Standards
#' 
#' @description Pediatric growth standard based on LMS data from the CDC and WHO.
#'
#' @details expect to call this from R after checking some functional
#' arguments within R.
#'
#' @param metric string
#' @param source string
#' @param male  integer
#' @param x is the age (in months), length (cm) or height (cm) as needed for
#' the metric.
#' @param qp the quantile or percentile, which ever is relevent for the type
#' @param type quantile, distribition, or zscore
#'
cppPGSF <- function(metric, source, male, x, qp, type) {
    .Call('_pedbp_cppPGSF', PACKAGE = 'pedbp', metric, source, male, x, qp, type)
}

